# This is a basic workflow to help you get started with Actions

name: "latest-blog"

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *" # Runs every 24 hours

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_blogs:
    name: "Update with Latest Blogs"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Fetching Repository content"
        uses: actions/checkout@main
        
      - name: "Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.1.1"
        with:
          USERNAME: "ctrlx-altf4"
          COUNT: 4
          STYLE: "list-ordered"
          BLOG_URL: "https://www.forehead.dev/"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
